[package]
name = "free-claude-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Core library for FreeClaudeDesktop"
license.workspace = true

[dependencies]
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
url.workspace = true
futures.workspace = true
getrandom = "0.4"
tokio.workspace = true
async-openai = { version = "0.41.1", features = ["chat-completion", "model", "responses", "byot", "rustls"] }
thiserror.workspace = true
tracing.workspace = true
keyring = "4.1.2"
[target.'cfg(target_os = "windows")'.dependencies]
winapi.workspace = true

[dev-dependencies]
axum = "0.8"
